### ISSUE TITLE
TWA not downloading

### ISSUE THREAD

**Issue by felipedario** [pwa-builder/pwabuilder-android-twa#6]
I'm not sure if this is the repository intended for this, but I can't download the PWA/TWA package for Androoid on  https://www.pwabuilder.com/publish. The "webview" link works. The PWA I'm testing is https://pwasa3651.websiteseguro.com

Also, `app/src/main/java/microsoft/com/pwa/PwaWebViewClient.java` in the legacy webview package is the same as `app/src/main/java/microsoft/com/pwa/PwaWebViewClient.java` in this repository, so: are they the same thing? I'm downloading the webview or the TWA package?

**Comment by JudahGabriel** [comment]
Hi, this isn't the right place to file this. Can you file the issue over at the [PWABuilder repo](https://github.com/pwa-builder/PWABuilder/issues/)?

**Comment by JudahGabriel** [comment]
p.s. I suspect the issue is that your PWA manifest is missing some important pieces of information:

![image](https://user-images.githubusercontent.com/312936/74766869-b23acc00-523a-11ea-9167-5afbfa145ea4.png)
