### ISSUE TITLE
Google requires to target SDK 29 for new apps

### ISSUE THREAD

**Issue by jcesarmobile** [pwa-builder/pwabuilder-android-twa#8]
For existing apps SDK 29 will be required in November.

The template targets SDK 28 at the moment
https://github.com/pwa-builder/pwabuilder-android-twa/blob/master/lib/template/app/build.gradle#L8

**Comment by JudahGabriel** [comment]
Our new platform uses TWA, rather than this old webview-based solution.

**Comment by jcesarmobile** [comment]
This is the TWA repository, isn't it?
or which one is the TWA one?

**Comment by JudahGabriel** [comment]
This is an old repo that needs to be archived. (Thanks for the reminder 😁). The new platform is over at https://github.com/pwa-builder/cloudAPK/

However, if you need to open an issue, please do so at our main [PWABuilder repository](https://github.com/pwa-builder/pwabuilder/issues)
