### ISSUE TITLE
java.lang.NoClassDefFoundError: aewt

### ISSUE THREAD

**Issue by drma-tech** [pwa-builder/pwabuilder-android-twa#9]
I received this notification on the google platform, after uploading the package

![image](https://user-images.githubusercontent.com/12803050/105180379-437c8780-5b09-11eb-9c2c-3cd0739b8186.png)

**Comment by JudahGabriel** [comment]
Can you open an issue on our [main repo](https://github.com/pwa-builder/pwabuilder/issues)?
